server:
  port: 8086
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
endpoint: oss-cn-beijing.aliyuncs.com
access-key-id: LTAI5tCiDpoKRikvwEcJeKkD
access-key-secret: KwHnYgd3hMoA8ZbvUGp0XStTqNq83I
bucket-name: yunjiaoyunji-oss
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 20
        min-idle: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cr146529
    url: jdbc:mysql://127.0.0.1:3306/yunjiaoyunji?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
logging:
  level:
    root: debug